version: "3.8"

services:
  ###########################################################################
  # 2) EPICS + Kafka micro-services
  ###########################################################################
  epics-simulator:
    build: ./epics-simulator # adjust folder name if different
    container_name: epics-simulator
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  epics-kafka-bridge:
    build: ./epics-kafka-bridge
    container_name: epics-kafka-bridge
    depends_on:
      - kafka
      - epics-simulator
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  epics-kafka-gateway:
    build: ./epics-kafka-gateway
    container_name: epics-kafka-gateway
    ports:
      - "8080:8080" # REST + WebSocket gateway
    depends_on:
      - kafka
      - epics-kafka-bridge
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
