version: "3.8"

services:
  ###########################################################################
  # 1) Kafka stack (Bitnami images)
  ###########################################################################
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_MAX_CLIENT_CONNECTIONS: 60
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.4
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,HOST://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  ###########################################################################
  # 2) EPICS + Kafka micro-services
  ###########################################################################
  epics-simulator:
    build: ./epics-simulator # adjust folder name if different
    container_name: epics-simulator
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  epics-kafka-bridge:
    build: ./epics-kafka-bridge
    container_name: epics-kafka-bridge
    depends_on:
      - kafka
      - epics-simulator
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  epics-kafka-gateway:
    build: ./epics-kafka-gateway
    container_name: epics-kafka-gateway
    ports:
      - "8080:8080" # REST + WebSocket gateway
    depends_on:
      - kafka
      - epics-kafka-bridge
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
